### ISSUE TITLE
Storage vs. ListStorage vs. MapStorage

### ISSUE THREAD

**Issue by assertchris** [mnapoli/BlackBox#10]
> In the end, it looks a lot like a MapStorage except IDs are autogenerated, but this auto-generation is problematic. I'm wondering if it could be made into a MapStorage, I'm wondering about the use cases of ListStorage at all (that can't be done with a Map). The only + side is the auto-generated ID, but maybe this concept can be brought back to MapStorage?

> I'm also thinking of removing the Storage interface, I don't see many use cases

You're totally right about ListStorage being similar! Perhaps the only interface we really need is MapStorage.

**Comment by mnapoli** [comment]
:+1: I'll remove the `Storage` one (and maybe rename `MapStorage` to `Storage`?)

I just have to figure out a clean way to keep `FileStorage` to store data into 1 file (it's useful to have for example 1 JSON file as the app "database").

**Comment by sagikazarmark** [comment]
Probably the only adapter where content formatting makes sense is the file adapter.

What do you think about using https://github.com/fire015/flintstone/ with the file adapter. It already implements the required logic, seems to be efficient to me. And lets you remove Storage...

**Comment by assertchris** [comment]
One of the ways MapStorage can be implemented [in files] is to make each line a serialised item. Then it becomes very similar to a queue except the whole file must be read at once.

**Comment by mnapoli** [comment]
@sagikazarmark allowing data transformers to be used on all storage types allows to do "ORM" kind of stuff, i.e. map PHP objects to primitive types (arrays mainly). Without being able to store objects, the whole thing would be much less interesting.

Using flintstone, why not but it seems a bit over-engineered for our needs.

I've removed `Storage` in a branch: https://github.com/mnapoli/BlackBox/compare/remove-storage-interface I'll review it later when my head is clearer (1:30 here), but I think we can rename `MapStorage` to `Storage` afterwards…

**Comment by sagikazarmark** [comment]
The reason why Storage might remain is that the storage implementations, that are based on pure PHP storage mechanism (meaning a file storage, or the Flysystem implementation) should still ba able to store data. The only possibility I can think of is serializing it and saving it, which is currently the responsibility of the Storage interface.

I don't mind if that specific interface is removed, but the need for that functionality is still needed (along with serializing logic).

**Comment by sagikazarmark** [comment]
Looking at `ListStorage` I am not even sure what that is good for.

**Comment by mnapoli** [comment]
> I don't mind if that specific interface is removed, but the need for that functionality is still needed (along with serializing logic).

Yep.

> Looking at `ListStorage` I am not even sure what that is good for.

We are discussing merging it all in one in #12.

**Comment by assertchris** [comment]
Looks like they will be merged into 1. Closing this for now.
