### ISSUE TITLE
ID values

### ISSUE THREAD

**Issue by assertchris** [mnapoli/BlackBox#11]
> There's one thing in CacheListStorage that's bothering me: $this->id is kind of like an auto-increment ID, but it lives in the class instance. In the next request, those IDs are back to 0, so getting/setting in the cache will overwrite/conflicts existing entries.

> The only + side is the auto-generated ID, but maybe this concept can be brought back to MapStorage?

I like the idea of using unique IDs. The only issue I see is some items having IDs and others not. Perhaps we can store the unique IDs and store the [user-assigned] key along with the value:

```php
$items = [
    "[unique id]" => [
        "key" => "foo",
        "value" => "bar",
    ],
    "[unique id]" => [
        "value" => "baz",
    ],
];
```

Then we can return numeric indices for unlabelled values and string keys for labelled values (like standard PHP). What do you think?

**Comment by mnapoli** [comment]
> The only issue I see is some items having IDs and others not.

Well if we auto-generate unique IDs when no ID is provided, then every items will have an ID right?

**Comment by assertchris** [comment]
+1 for auto-generated unique ID.
