### ISSUE TITLE
Library scope and goals

### ISSUE THREAD

**Issue by mnapoli** [mnapoli/BlackBox#17]
Hey guys, happy to see we are motivated to make this a real thing.

I'm opening this issue to discuss in one place what we want to do with this library, because I think all the topics of interfaces, there methods, the queues, etc are impacted.

Originally, I created this project with simplicity in mind. Basically I read [this](http://blog.ircmaxell.com/2014/10/an-open-letter-to-php-fig.html) and wanted to try to build something very extensible out of the simplest interfaces.

I am not against adding features, e.g. transactions, TTL, queries, … But as long as the core concepts stay simple. By combining simple stuff we can create awesome features.

E.g. want to add TTL? Here is an adapter! Want namespaces, here is another one!

Another example: I would like in the future to add querying. Of course not every backend supports that, and not every user need that, so `MapStorage` (or whatever the interface) wouldn't stay as simple as possible.

But there would be an *optional* API to do queries, e.g.:

```
$bobIssues = (new Query($issueStorage))
    ->filter('author', 'bob')
    ->sort('creationDate')
    ->slice(10, 20);
```

(don't focus on the technical details it's just an example)

Such query would be executed lazily (i.e. only when it is traversed), exactly like [Doctrine's Criterias](http://doctrine-orm.readthedocs.org/en/latest/reference/working-with-associations.html#filtering-collections). For backend that don't support such queries, the filtering/sorting/… would be executed in-memory using PHP code. Being able to query JSON files, Redis or MySQL with the same API would be awesome!

So I'd like to try to keep the base interface/API as simple as possible and push towards SRP, ISP and composition (in the OOP sense). But I'm really open to discuss that.

E.g. adding methods to add/check/remove items from a storage make sense. Today we can use `set($key, null)` to remove, but maybe a dedicated `remove($key)` method makes more sense. `get($key)` also returns null if the element doesn't exist, but having a `has($key)` might make sense too. `add()` would make sense to solve the "generated ID" problem.

However I would like, if it is possible, to avoid [`flush()` like in KeyValueStore](https://github.com/adammbalogh/key-value-store). If we want to have transactions, we could make an adapter, or an interface. If we want to have batch operations, we could also try to solve it with an adapter. Same thing for TTL operations, I'd rather avoid them or put them in an adapter that would apply the same TTL for every item of a storage (we rarely need ≠ TTL for each cache entry).

@assertchris @sagikazarmark what's your take on this?

**Comment by sagikazarmark** [comment]
Hey

I think we are on the same track. Simplicity is the keyword which is needed nowadays to create clean, useful, decent packages.

Honestly, transactions and queries are out of scope IMO. This aims to be a simple storage library, so probably the only "query" you need are the basic operations you can execute (get/set/has/delete).

The reason I think that remove is better is that null is also a valid value IMO. This is something which probably also a question in the upcoming Cache PSR: are null values a miss  or they can be a hit. We should also discuss it, but we will probably end up simply not thinking about null values. So I would say delete is needed.

I have no problem with not exposing a flush method in the public interface, but flushing is needed in some cases (I don't remember where, need to check the KeyValueStore implementation), so if it is solved internally, I don't mind. Probably in __destruct?

About TTL: it makes sense in caching. In storage, it doesn't really. You don't set TTL for your records in a MySQL database. :smile: I would say, it is an application responsibility if someone wants to set TTL. For example if session stored in it, the session handler solves the TTL.

All in all: I am absolutely motivated and feel the need for a storage library like this in the PHP community.

**Comment by sagikazarmark** [comment]
When I mentioned flushing, I exactly meant this case:
https://github.com/mnapoli/BlackBox/blob/master/src/Adapter/MapAdapter.php#L50

Clear overhead. Should be read once, and saved at the end IMO.

**Comment by assertchris** [comment]
+1 for simplicity.

**Comment by mnapoli** [comment]
Sorry guys for taking so long to get back.

I just discovered this yesterday: [key-value-store](https://github.com/webmozart/key-value-store). Yet another one, still in beta, so I'll try to see if he wants to team up too. He has a very solid implementation of JSON serialization, so there's definitely some interesting things there. I however prefer the approach here of being able to use any "transformer" with any storage: e.g. his JSON serializer is hardcoded in the file storage, or the Redis store uses hardcoded `serialize()` :( .
